### ISSUE TITLE
Function failed on loading user code

### ISSUE THREAD

**Issue by grant** [JustinBeckwith/gcx#6]
While trying to get a hello world sample working, I saw an error with functions loading user code.

Could this repo have step-by-step instructions for hello world? These are my rough steps to reproduce:

```sh
gcloud auth login
gcloud auth application-default login
gcloud config set project 'YOUR-AWESOME-PROJECT' # changed
npm i -g .
mkdir testgcx && cd testgcx
# Download index.js & package.json into this dir
gcx deploy myhook --runtime nodejs10 --trigger-http
```

Output:

```
gcx deploy myhook --runtime nodejs10 --trigger-http

    🤖 I generated a '.gcloudignore' file in the target directory.
       This file contains a list of glob patterns that should be ingored
       in your deployment. It works just like a .gitignore file 💜

🤖 Deployment initialized.
📦 Source code packaged.
🛸 Source uploaded to cloud.
⠙ Deploying function...Error: {"code":3,"message":"Function failed on loading user code. Error message: Error: cannot communicate with function."}
    at Deployer._poll (/Users/timmerman/Downloads/testgcx/gcx/build/src/index.js:82:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by JustinBeckwith** [comment]
Oh weird. Can you share your JavaScript and package.json?

**Comment by grant** [comment]
```.gcloudignore
# This file specifies files that are *not* uploaded to Google Cloud Platform
# using gcloud. It follows the same syntax as .gitignore, with the addition of
# "#!include" directives (which insert the entries of the given .gitignore-style
# file at that point).
#
# For more information, run:
#   $ gcloud topic gcloudignore
#
.gcloudignore
# If you would like to upload your .git directory, .gitignore file or files
# from your .gitignore file, remove the corresponding line
# below:
.git
.gitignore

node_modules
#!include:.gitignore

test/
```

```js
/**
 * Responds to any HTTP request.
 *
 * @param {!express:Request} req HTTP request context.
 * @param {!express:Response} res HTTP response context.
 */
exports.helloWorld = (req, res) => {
  let message = req.query.message || req.body.message || 'Hello World!';
  res.status(200).send(message);
};
```

```json
{
  "name": "sample-http",
  "version": "0.0.1"
}
```

**Comment by JustinBeckwith** [comment]
I am having trouble reproducing the specific error you're getting.  That having been said - can you try this?

```
npx gcx deploy helloWorld
```

**Comment by grant** [comment]
I think it's just user error.
`myhook` is just the placeholder name for the function name. Although, it be great if the error was clearer.
Works fine after fixing the function name.
Thanks for the help!

**Comment by JustinBeckwith** [comment]
Yeah so I think I see the problem.  You have a function named `helloWorld`, but your cloud function is called `myhook`.

**Comment by JustinBeckwith** [comment]
FWIW - I get a *much* better error when I do this:

```
Deploying function...Error: {"code":3,"message":"Function failed on loading user code. Error message: Node.js module defined by file index.js is expected to export function named ohai2"}
```

**Comment by grant** [comment]
Not sure how you get that better error, but thanks again. May suggest PRs.

**Comment by gkp-dev** [comment]
I got this error 

`### Function failed on loading user code. This is likely due to a bug in the user code. Error message: Error: please examine your function logs to see the error cause`

But I don't know how to resolve it. I checked the name of the function, but it's the same as my local one.
I verified the code locally and there is no errors. So I hope someone can help me with it
